package com.cdkj.model.wechat.pojo;


import com.cdkj.common.base.model.pojo.BaseModel;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wechat_main_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class WechatMainInfo extends BaseModel {

    /**
     * Database Column Remarks:
     * 授权方昵称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.NICK_NAME
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     * 授权方头像
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.HEAD_IMG
     *
     * @mbg.generated
     */
    private String headImg;

    /**
     * Database Column Remarks:
     * 授权方公众号类型，0代表订阅号，1代表由历史老帐号升级后的订阅号，2代表服务号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.SERVICE_TYPE_INFO
     *
     * @mbg.generated
     */
    private Integer serviceTypeInfo;

    /**
     * Database Column Remarks:
     * 授权方认证类型，-1代表未认证，0代表微信认证，1代表新浪微博认证，2代表腾讯微博认证，3代表已资质认证通过但还未通过名称认证，4代表已资质认证通过、还未通过名称认证，但通过了新浪微博认证，5代表已资质认证通过、还未通过名称认证，但通过了腾讯微博认证
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.VERIFY_TYPE_INFO
     *
     * @mbg.generated
     */
    private Integer verifyTypeInfo;

    /**
     * Database Column Remarks:
     * 授权方公众号的原始ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     * 授权方公众号所设置的微信号，可能为空
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.ALIAS
     *
     * @mbg.generated
     */
    private String alias;

    /**
     * Database Column Remarks:
     * 二维码图片的URL，开发者最好自行也进行保存
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.QRCODE_URL
     *
     * @mbg.generated
     */
    private String qrcodeUrl;

    /**
     * Database Column Remarks:
     * 公众号的主体名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.PRINCIPAL_NAME
     *
     * @mbg.generated
     */
    private String principalName;

    /**
     * Database Column Remarks:
     * 公众号签名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.SIGNATURE
     *
     * @mbg.generated
     */
    private String signature;

    /**
     * Database Column Remarks:
     * 授权方appid
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.AUTHORIZER_APPID
     *
     * @mbg.generated
     */
    private String authorizerAppid;

    /**
     * Database Column Remarks:
     * 授权方 刷新用令牌信息
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_main_info.AUTHORIZER_REFRESH_TOKEN
     *
     * @mbg.generated
     */
    private String authorizerRefreshToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.NICK_NAME
     *
     * @return the value of wechat_main_info.NICK_NAME
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.NICK_NAME
     *
     * @param nickName the value for wechat_main_info.NICK_NAME
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.HEAD_IMG
     *
     * @return the value of wechat_main_info.HEAD_IMG
     * @mbg.generated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.HEAD_IMG
     *
     * @param headImg the value for wechat_main_info.HEAD_IMG
     * @mbg.generated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.SERVICE_TYPE_INFO
     *
     * @return the value of wechat_main_info.SERVICE_TYPE_INFO
     * @mbg.generated
     */
    public Integer getServiceTypeInfo() {
        return serviceTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.SERVICE_TYPE_INFO
     *
     * @param serviceTypeInfo the value for wechat_main_info.SERVICE_TYPE_INFO
     * @mbg.generated
     */
    public void setServiceTypeInfo(Integer serviceTypeInfo) {
        this.serviceTypeInfo = serviceTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.VERIFY_TYPE_INFO
     *
     * @return the value of wechat_main_info.VERIFY_TYPE_INFO
     * @mbg.generated
     */
    public Integer getVerifyTypeInfo() {
        return verifyTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.VERIFY_TYPE_INFO
     *
     * @param verifyTypeInfo the value for wechat_main_info.VERIFY_TYPE_INFO
     * @mbg.generated
     */
    public void setVerifyTypeInfo(Integer verifyTypeInfo) {
        this.verifyTypeInfo = verifyTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.USER_NAME
     *
     * @return the value of wechat_main_info.USER_NAME
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.USER_NAME
     *
     * @param userName the value for wechat_main_info.USER_NAME
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.ALIAS
     *
     * @return the value of wechat_main_info.ALIAS
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.ALIAS
     *
     * @param alias the value for wechat_main_info.ALIAS
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.QRCODE_URL
     *
     * @return the value of wechat_main_info.QRCODE_URL
     * @mbg.generated
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.QRCODE_URL
     *
     * @param qrcodeUrl the value for wechat_main_info.QRCODE_URL
     * @mbg.generated
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.PRINCIPAL_NAME
     *
     * @return the value of wechat_main_info.PRINCIPAL_NAME
     * @mbg.generated
     */
    public String getPrincipalName() {
        return principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.PRINCIPAL_NAME
     *
     * @param principalName the value for wechat_main_info.PRINCIPAL_NAME
     * @mbg.generated
     */
    public void setPrincipalName(String principalName) {
        this.principalName = principalName == null ? null : principalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.SIGNATURE
     *
     * @return the value of wechat_main_info.SIGNATURE
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.SIGNATURE
     *
     * @param signature the value for wechat_main_info.SIGNATURE
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.AUTHORIZER_APPID
     *
     * @return the value of wechat_main_info.AUTHORIZER_APPID
     * @mbg.generated
     */
    public String getAuthorizerAppid() {
        return authorizerAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.AUTHORIZER_APPID
     *
     * @param authorizerAppid the value for wechat_main_info.AUTHORIZER_APPID
     * @mbg.generated
     */
    public void setAuthorizerAppid(String authorizerAppid) {
        this.authorizerAppid = authorizerAppid == null ? null : authorizerAppid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_main_info.AUTHORIZER_REFRESH_TOKEN
     *
     * @return the value of wechat_main_info.AUTHORIZER_REFRESH_TOKEN
     * @mbg.generated
     */
    public String getAuthorizerRefreshToken() {
        return authorizerRefreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_main_info.AUTHORIZER_REFRESH_TOKEN
     *
     * @param authorizerRefreshToken the value for wechat_main_info.AUTHORIZER_REFRESH_TOKEN
     * @mbg.generated
     */
    public void setAuthorizerRefreshToken(String authorizerRefreshToken) {
        this.authorizerRefreshToken = authorizerRefreshToken == null ? null : authorizerRefreshToken.trim();
    }

}