package com.cdkj.model.wechat.pojo;


import com.cdkj.common.base.model.pojo.BaseModel;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wechat_func_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class WechatFuncInfo extends BaseModel {

    /**
     * Database Column Remarks:
     * 主表ID srv_wechat_main_info.ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_func_info.MAIN_ID
     *
     * @mbg.generated
     */
    private String mainId;

    /**
     * Database Column Remarks:
     * 授权给开发者的权限集列表，ID为1到26分别代表：
     * 1、消息管理权限
     * 2、用户管理权限
     * 3、帐号服务权限
     * 4、网页服务权限
     * 5、微信小店权限
     * 6、微信多客服权限
     * 7、群发与通知权限
     * 8、微信卡券权限
     * 9、微信扫一扫权限
     * 10、微信连WIFI权限
     * 11、素材管理权限
     * 12、微信摇周边权限
     * 13、微信门店权限
     * 14、微信支付权限
     * 15、自定义菜单权限
     * 16、获取认证状态及信息
     * 17、帐号管理权限（小程序）
     * 18、开发管理与数据分析权限（小程序）
     * 19、客服消息管理权限（小程序）
     * 20、微信登录权限（小程序）
     * 21、数据分析权限（小程序）
     * 22、城市服务接口权限
     * 23、广告管理权限
     * 24、开放平台帐号管理权限
     * 25、开放平台帐号管理权限（小程序）
     * 26、微信电子发票权限
     * <p>
     * 请注意：
     * 1）该字段的返回不会考虑公众号是否具备该权限集的权限（因为可能部分具备），请根据公众号的帐号类型和认证情况，来判断公众号的接口权限。
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_func_info.FUNC_ID
     *
     * @mbg.generated
     */
    private Integer funcId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_func_info.MAIN_ID
     *
     * @return the value of wechat_func_info.MAIN_ID
     * @mbg.generated
     */
    public String getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_func_info.MAIN_ID
     *
     * @param mainId the value for wechat_func_info.MAIN_ID
     * @mbg.generated
     */
    public void setMainId(String mainId) {
        this.mainId = mainId == null ? null : mainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_func_info.FUNC_ID
     *
     * @return the value of wechat_func_info.FUNC_ID
     * @mbg.generated
     */
    public Integer getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_func_info.FUNC_ID
     *
     * @param funcId the value for wechat_func_info.FUNC_ID
     * @mbg.generated
     */
    public void setFuncId(Integer funcId) {
        this.funcId = funcId;
    }

}